#cloud-config
write_files:
  - path: /run/secrets/google_application_credentials.json
    permissions: '0400'
    owner: nixos:users
    encoding: b64
    content: |
      ${google_application_credentials}