name: Build and push nixos image
on:
  push:
    branches:
      - main
    paths:
      - "nixos/**"
      - "terraform/image/**"
      - ".github/workflows/image.yml"
      - "scripts/nix-build.sh"
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v5
      - uses: opentofu/setup-opentofu@v1
      - name: Build
        run: ./scripts/nix-build.sh
      - name: Publish
        run: |
          cd terraform/image
          tofu init
          echo Starting apply
          tofu apply -auto-approve -replace="openstack_images_image_v2.frontend-image" -replace="openstack_images_image_v2.backend-image"
        env:
          PG_CONN_STR: ${{ secrets.PG_CONN_STR }}
          OS_AUTH_URL: ${{ secrets.OS_AUTH_URL }}
          OS_APPLICATION_CREDENTIAL_SECRET: ${{ secrets.OS_APPLICATION_CREDENTIAL_SECRET }}
          OS_APPLICATION_CREDENTIAL_ID: ${{ secrets.OS_APPLICATION_CREDENTIAL_ID }}
  deploy:
    uses: ./.github/workflows/skyhigh.yml